### ISSUE TITLE
Cannot find the installation script

### ISSUE THREAD

**Issue by ronneylira** [antiprism/turnandrun#1]
Hi, 

Thanks for the project! I was trying to install it on my setup. Sadly the file wget -N http://pitastic.com/turnandrun/packages/turnandrun_install_latest.sh is not available. I get a 404
when I try to access pitastic/turnandrun I do not have access. Is the file gone or is it me that don't know how to login ?

**Comment by antiprism** [comment]
Hi

Thanks for reporting this. The instructions are incorrect, as there are separate scripts for Moode and Volumio. Please run either...

For Moode
```
wget -N http://pitastic.com/turnandrun/packages/turnandrun_moode_install_latest.sh
sudo bash turnandrun_moode_install_latest.sh
```
For Volumio
```
wget -N http://pitastic.com/turnandrun/packages/turnandrun_volumio_install_latest.sh
sudo bash turnandrun_volumio_install_latest.sh
```
However, as there has been little interest in this project I haven't updated the binaries, and it is possible they will not work on the latest version of Moode and Volumio.

Adrian.

**Comment by ronneylira** [comment]
Thanks for the quick response :)
I'm struggling now with my volumio restarting constantly. Don't know if it was the soldering or the configuration. 

Did you experience that?

**Comment by antiprism** [comment]
Hi

No, I have never had this issue, but you could review the power cable and power adapter.

Adrian.
