### ISSUE TITLE
Potentiometer causing restarts

### ISSUE THREAD

**Issue by ronneylira** [antiprism/turnandrun#2]
Hi Adrian,

me again :) looks like it starts to restart whenever I connect the pot to my radio.
I noticed that it is a 50K potentiometer instead of the one you recommended. Do you think that might be the reason behind it?

**Comment by antiprism** [comment]
Hi

I don't know a lot about electronics, but I don't think it should make a difference to use a 50k potentiometer. This thread says 10k is normal with ADS1115, but 50k should work

   https://discourse.agopengps.com/t/no-was-reading/7817

Maybe, review your wiring, and check for a short across the potentiometer. Also, try a different potentiometer, if you have one available.

Adrian.

**Comment by ronneylira** [comment]
Hi Adrian,
Thanks for trying to help me out. I found some guidance in another forum, and they provided me with the idea that the fact that the potentiometer is still being attached to the old radio circuits might be the cause of the issue. Being the dingdong that I am I had no idea a turned-off radio would still be able to "steal" power from the pi and restart it.

**Comment by antiprism** [comment]
Ah, ok. Thanks for updating with the explanation of the issue.
Adrian.
